### PR TITLE
Added support for private git repositories using ssh.

### PR DESCRIPTION
**Pull request by oysmal**
I noticed that i could not use hygen-add with our company's private bitbucket repositories. hygen-add did not register git+ssh://git@bitbucket.org:/xxx/repository as an URL. By changing the regex testing for isUrl, this problem is solved.

### CODE REVIEW

**Comment by oysmal** [comment]
Edit: The project had not been built properly. Tested now and it works with the new "Rebuild" commit.

**Comment by jondot** [comment]
Amazing! thanks!

**Comment by oysmal** [comment]
No problem! It is a nice tool :) Could I trouble you to re-publish to NPM? The repository version is stuck at 1.0.5.

**Comment by jondot** [comment]
Hmm in fact I immediately did. Looks like the CI pipeline didn’t publish, thanks for letting me know!

**Pull request merged**
